// packages/engine/src/lib/components/Selector.svelte
<script lang="ts">
    interface Props {
        x?: number
        y?: number
        width?: number
        height?: number
    }

    let { x = 0, y = 0, width = 0, height = 0 }: Props = $props()
</script>

<div
    class="selector"
    style="
        left: {x}px;
        top: {y}px;
        width: {width}px;
        height: {height}px;
    "
></div>

<style>
    .selector {
        position: absolute;
        pointer-events: none;
        box-sizing: border-box;
        border: 2px solid #1a73e8;
        background: rgba(26, 115, 232, 0.08);
        z-index: 10;
    }
</style>

// src/components/selector/selector.tsx
import { selectorStore } from './store'
import { observer, useLocalStore } from 'mobx-react'
export const SelectorComponent = observer(() => {
    const store = useLocalStore(() => selectorStore)
    const { startCell, endCell } = store
    if (!startCell) return null
    let _endCell = endCell ?? startCell
    const leftMost = startCell.position.startCol < _endCell.position.startCol ? startCell : _endCell
    const rightMost = startCell.position.startCol < _endCell.position.startCol ? _endCell : startCell
    const topMost = startCell.position.startRow < _endCell.position.startRow ? startCell : _endCell
    const bottomMost = startCell.position.endRow > _endCell.position.endRow ? startCell : _endCell
    return (
        <div
            className='selector'
            style={{
                position: 'absolute',
                width: `${rightMost.position.endCol - leftMost.position.startCol}px`,
                height: `${bottomMost.position.endRow - topMost.position.startRow}px`,
                left: `${leftMost.position.startCol}px`,
                top: `${topMost.position.startRow}px`,
                border: '2px solid rgba(31, 187, 125, 0.4)',
                boxSizing: 'content-box'
            }}
        >
        </div>
    )
})
