// src/components/dnd/dnd.tsx
import styles from './dnd.module.scss'
import { observer, useLocalStore } from 'mobx-react'
import { dndStore } from './store'

const BORDER_WIDTH = 2
const POS = (position: number | null) => `${(position ?? 0) - BORDER_WIDTH}px`
export const DndComponent = observer(() => {
    const store = useLocalStore(() => dndStore)
    console.log('dnd component', store)
    const {
        dragging,
        range,
    } = store
    if (!range) return null
    const { x, y, width, height, draggingX, draggingY } = range
    return (
        <div className={styles.host}>
            <div
                className={styles['dragging-handle']}
                style={{
                    left: POS(x),
                    top: POS(y),
                    width: `${width}px`,
                    height: `${height}px`,
                }}
                data-selector-dnd-handle
            >
                <div
                    className={styles['dragging-mask']}
                    data-selector-dnd-mask
                ></div>
            </div>
            <div
                className={styles.dragging}
                style={{
                    display: dragging ? 'block' : 'none',
                    left: POS(draggingX),
                    top: POS(draggingY),
                    width: `${width}px`,
                    height: `${height}px`,
                }}
            ></div>
        </div>
    )
})

// web/app/dnd/dnd.component.ts
import {Component, ChangeDetectionStrategy, Input} from '@angular/core'
const BORDER_WIDTH = 2
const POS = (position: number | null) => `${(position ?? 0) - BORDER_WIDTH}px`

@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'logi-dnd',
    styleUrls: ['./dnd.component.scss'],
    templateUrl: './dnd.component.html',
})
export class DndComponent {
    @Input() x: number | null = -1
    @Input() y: number | null = -1
    @Input() width: number | null = -1
    @Input() height: number | null = -1
    @Input() draggingX: number | null = -1
    @Input() draggingY: number | null = -1
    get borderStyle() {
        return {
            left: POS(this.x),
            top: POS(this.y),
            width: `${this.width}px`,
            height: `${this.height}px`,
        }
    }

    get draggingStyle() {
        const invalid = () => {
            if (this.draggingX === this.x && this.draggingY === this.y)
                return true
            if (this.draggingX === null || this.draggingY === null)
                return true
            if (this.draggingX < 0 || this.draggingY < 0)
                return true
            return false
        }
        return {
            display: invalid() ? 'none' : 'block',
            left: POS(this.draggingX),
            top: POS(this.draggingY),
            width: `${this.width}px`,
            height: `${this.height}px`,
        }
    }
}

<div class="border" [ngStyle]="borderStyle"></div>
<div class="dragging" [ngStyle]="draggingStyle"></div>
