// web/app/top-bar/top-bar.component.ts
import {
    Component,
    Input,
    Output,
    EventEmitter,
    ChangeDetectionStrategy,
} from '@angular/core'
import {SetAttrEvent} from './content'
import {SelectedCell} from '@logi-sheets/web/app/canvas'
import {MainMenuType} from './main-menu.component'

@Component({
    selector: 'logi-top-bar',
    templateUrl: './top-bar.component.html',
    styleUrls: ['./top-bar.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TopBarComponent {
    @Output() readonly setAttrEvent$ = new EventEmitter<SetAttrEvent>()
    @Input() selectedCell?: SelectedCell
    mainMenuType = MainMenuType.START
    mainMenuTypeEnum = MainMenuType
    mainMenuChange(type: MainMenuType): void {
        this.mainMenuType = type
    }
}

<logi-main-menu class="main-menu" [currType]='mainMenuType' (mainMenuChanged$)='mainMenuChange($event)'>
</logi-main-menu>
<div class="content">
    <ng-container [ngSwitch]='mainMenuType'>
        <logi-start class="top-bar-start content-detail" *ngSwitchCase='mainMenuTypeEnum.START'
            [selectedCell]='selectedCell'>
        </logi-start>
    </ng-container>
</div>

// src/components/top-bar/index.tsx
import {SetAttrEvent} from './content'
import {SelectedCell} from 'components/canvas'
import {MainMenuType, MainMenu} from './main-menu'
import { useState } from 'react'
import styles from './top-bar.module.scss'
import {Start} from './content'

export interface TopBarProps {
    readonly selectedCell?: SelectedCell
    readonly setAttr?: (e: SetAttrEvent) => void
}

export const TopBar = ({selectedCell, setAttr}: TopBarProps) => {
    const [mainMenuType, setMainMenuType] = useState(MainMenuType.START)
    return (
        <div className={styles['host']}>
            <div className={styles['main-menu']}>
                <MainMenu currType={mainMenuType} mainMenuChanged$={setMainMenuType}></MainMenu>
            </div>
            <div className={styles["content"]}>
                <div className={styles['top-bar-start']}>
                    {
                        mainMenuType === MainMenuType.START ?
                            <Start selectedCell={selectedCell}></Start>
                        : null
                    }
                </div>
            </div>
        </div>
    )
}
