// web/app/sheets-tab/sheets-tab.component.ts
import {
    Component,
    OnInit,
    OnDestroy,
    ChangeDetectionStrategy,
} from '@angular/core'
import {
    PayloadBuilder,
    SheetShiftBuilder,
    ShiftTypeEnum,
    TransactionBuilder,
    _Payload_Payload_oneof,
} from '@logi-pb/network/src/proto/message_pb'
import {DataService} from '@logi-sheets/web/core/data'
import {Subscription, BehaviorSubject} from 'rxjs'

@Component({
    selector: 'logi-sheets-tab',
    templateUrl: './sheets-tab.component.html',
    styleUrls: ['./sheets-tab.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetsTabComponent implements OnInit, OnDestroy {
    public constructor(
        public readonly dataSvc: DataService,
    ) {}
    tabs$ = new BehaviorSubject<readonly string[]>([])
    active = 0

    ngOnInit() {
        this._updateSheets()
        this._subs.add(this.dataSvc.backend.render$.subscribe(() => {
            this._updateSheets()
        }))
    }

    ngOnDestroy() {
        this._subs.unsubscribe()
    }

    onTabChange(i: number) {
        this.active = i
        this.dataSvc.sheetSvc.setActiveSheet(i)
    }

    add() {
        const shift = new SheetShiftBuilder()
            .sheetIdx(this.active)
            .type(ShiftTypeEnum.INSERT)
            .build()
        const payload = new PayloadBuilder()
            .payloadOneof(shift, _Payload_Payload_oneof.SHEET_SHIFT)
            .build()
        const transaction = new TransactionBuilder().payloads([payload]).build()
        this.dataSvc.backend.send(transaction)
    }

    private _subs = new Subscription()
    private _updateSheets() {
        const sheets = this.dataSvc.sheetSvc.getSheets().map(s => s.name)
        this.tabs$.next(sheets)
    }
}

<div class="tab" [ngClass]="{'active':i === active}" *ngFor="let sheetname of tabs$ | async;let i=index"
    (click)='onTabChange(i)' [index]="i" logi-sheet-tab-contextmenu>{{sheetname}}</div>
<button (click)="add()">add</button>

// src/components/sheets-tab/index.tsx
import { useState, FC, useEffect } from 'react'
import styles from './sheets-tab.module.scss'
import {ContextMenuComponent} from './contextmenu'
import {InsertSheetBuilder} from '@/api'
import { Backend, SheetService } from '@/core/data'
import { useInjection } from '@/core/ioc/provider'
import { TYPES } from '@/core/ioc/types'
import { Subscription } from 'rxjs'

export type SheetsTabprops = Record<string, unknown>

export const SheetsTabComponent: FC<SheetsTabprops> = () => {
    const BACKEND_SERVICE = useInjection<Backend>(TYPES.Backend)
    const SHEET_SERVICE = useInjection<SheetService>(TYPES.Sheet)
    const getSheets = () =>
        SHEET_SERVICE.getSheets().map(s => s.name)
    const [sheets, setSheets] = useState(getSheets())
    const [active, setActive] = useState(0)
    const [isOpen, setIsOpen] = useState(false)

    useEffect(() => {
        const subs = new Subscription()
        subs.add(BACKEND_SERVICE.render$.subscribe(() => {
            setSheets(getSheets())
        }))
        return () => {
            subs.unsubscribe()
        }
    }, [])

    const onTabChange = (i: number) => {
        setActive(i)
        SHEET_SERVICE.setActiveSheet(i)
    }

    const add = () => {
        const payload = new InsertSheetBuilder()
            .sheetIdx(active)
            .build()
        BACKEND_SERVICE.sendTransaction([payload])
    }
    return (
        <div className={styles['host']}>
            <div className={styles['pre-btns']}></div>
            {sheets.map((sheet, i) => (
                <div className={['tab', `${i === active ? 'active' : ''}`].join(' ')}
                    onClick={() => onTabChange(i)}
                    onContextMenu={() => setIsOpen(true)}
                    key={i}
                >{sheet}</div>))
            }
            <div className={styles['add-btn']} onClick={add}>+</div>
            <ContextMenuComponent
                isOpen={isOpen}
                setIsOpen={setIsOpen}
                index={active}
                sheetnames={sheets}
            ></ContextMenuComponent>
        </div>
    )
}
